version: '3.3'
services:
  portainer:
    container_name: portainer
    restart: unless-stopped
    ports:
      - '9000:9000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/docker/portainer:/data'
    image: 'portainer/portainer:linux-arm'
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    image: containrrr/watchtower
  adguardhome:
    container_name: adguardhome
    image: 'adguard/adguardhome:latest'
    restart: always
    volumes:
      - '/docker/adguard/workdir:/opt/adguardhome/work'
      - '/docker/adguard/confdir:/opt/adguardhome/conf'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '68:68/tcp'
      - '80:80/tcp'
      - '443:443/tcp'
      - '853:853/tcp'
      - '3000:3000/tcp'
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/heimdall/config:/config
    ports:
      - 8080:80
    restart: unless-stopped
  homebridge:
    image: homebridge/homebridge:latest
    container_name: hb
    restart: always
    network_mode: host
    volumes:
      - '/docker/homebridge:/homebridge'
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
  it-tools:
    image: 'corentinth/it-tools:latest'  # The Docker image to use.
    ports:
      - '8000:80'
    restart: unless-stopped
    container_name: it-tools

